all: false
debug: false
chart-dirs:
  - charts
charts:
  - charts/stwgs-content-api
check-increment-version: false
helm-extra-args: --timeout 800s
validate-chart-schema: false
validate-maintainers: false
